import type { DiscoveryRun, TreeNode } from "./types";

const shihuaNodes: TreeNode[] = [
  {
    id: "root",
    parentId: null,
    label: "Dataset",
    claim: "Shihua Cave paleoclimate record",
    status: "root",
    depth: 0,
    visits: 6,
    value: 3.85,
    summary: "Seven aligned records spanning 11.32–10.0 ka BP, including isotope, lamina, dating, and age-ensemble measurements.",
    metrics: [
      { label: "Files", value: "7" },
      { label: "Variables", value: "42" },
      { label: "Age models", value: "1,000" },
    ],
  },
  {
    id: "H1",
    parentId: "root",
    label: "H1 · lead–lag",
    claim: "δ18O isotopic shifts lead δ13C excursions during abrupt centennial cooling events.",
    status: "refuted",
    depth: 1,
    visits: 1,
    value: 0.8,
    reward: 0.8,
    belief: { prior: 0.69, literature: 0.58, seed: 0.13 },
    verdict: "no independent data",
    empiricalSupport: false,
    summary: "The records move synchronously rather than with the predicted multi-decadal lag. The strongest lag term was not significant after correction.",
    rationale: "Age-ensemble cross-correlation and ARDL tests both favor contemporaneous coupling, consistent with fast karst hydrology rather than delayed vegetation response.",
    metrics: [
      { label: "Optimal lag", value: "0 yr" },
      { label: "ARDL p", value: "0.801" },
      { label: "Cointegration p", value: "0.0178" },
    ],
    sources: [
      { title: "Stable isotope records", source: "Dataset S2.xlsx", kind: "seed", note: "447 co-located δ18O and δ13C measurements" },
      { title: "Age ensemble", source: "Dataset S5.xlsx", kind: "seed", note: "1,000 chronology realizations" },
      { title: "Speleothem response dynamics", source: "Wong & Breecker, 2015", kind: "literature", note: "Mechanistic prior and confounders" },
    ],
    code: `# Lag robustness across the chronology ensemble\nfor age_model in ensemble:\n    aligned = align_proxies(d18o, d13c, age_model)\n    lags.append(cross_correlation(aligned, max_lag=30))\n\nci = np.quantile(lags, [0.025, 0.975])`,
    whyProposed: "Oxygen isotopes can respond rapidly to atmospheric circulation while carbon isotopes may integrate slower soil and vegetation processes. The engine selected this candidate because the two proxies are co-located, highly resolved, and the provided chronology ensemble makes lead–lag uncertainty directly testable.",
    literatureRationale: "The literature supports different response times for atmospheric and ecological processes, but fast prior calcite precipitation and epikarst mixing can create synchronous movement. The prior therefore favored the hypothesis only moderately.",
    seedRationale: "Cross-correlation peaks at zero years across the full record. In the primary 10.3 ka event, the five-year lag term is not significant (p = 0.801), while contemporaneous coupling is strong. The predicted lead is not supported.",
    test: {
      question: "Do δ18O shifts consistently precede δ13C excursions by a positive, non-zero lag during abrupt cooling events?",
      population: "447 paired CS01C isotope measurements spanning 10.18–11.32 ka BP, propagated through 1,000 admissible age models.",
      prediction: "The maximum cross-correlation occurs at a positive δ18O lead, and lagged ARDL terms remain significant after correction.",
      method: "Event-window and full-record cross-correlation, Engle–Granger cointegration, ARDL lag regression, and chronology-ensemble robustness analysis.",
      successCriteria: ["Positive optimal lag in both predefined events", "Lagged coefficient p < 0.05 after correction", "Direction preserved across at least 80% of age models"],
    },
    sandbox: { id: "verification_node_000001", runtime: "Cloud Run · sandbox do", image: "urithiru-sandbox:latest", region: "europe-west1", startedAt: "19:09:18 UTC", duration: "03m 47s", exitCode: 0, stdout: "Cross-correlation and ARDL analysis completed across 1,000 age-model realizations.\nOptimal lag (full record): 0 yr\nARDL lag-5 p-value: 0.8013\nDirection supported: False", stderr: "" },
    logs: [
      { time: "19:09:18.114", level: "info", source: "orchestrator", message: "submitted verification_node_000001 to Cloud Run" },
      { time: "19:09:20.481", level: "success", source: "sandbox", message: "sandbox ready; 7 dataset files mounted read-only" },
      { time: "19:09:34.022", level: "info", source: "verification", message: "Phase A complete; p_search.json saved before seed access" },
      { time: "19:10:07.663", level: "info", source: "verification", message: "running cross-correlation over 1,000 chronology realizations" },
      { time: "19:12:41.304", level: "warning", source: "verification", message: "predicted lag not detected; contemporaneous model preferred" },
      { time: "19:13:05.901", level: "success", source: "sandbox", message: "result.json validated; container exited with code 0" },
    ],
    artifacts: [
      { name: "goal.txt", path: "sandbox_artifacts/verification_node_000001/goal.txt", size: "13.0 KB", kind: "prompt", stage: "verification", savedAt: "19:09:20" },
      { name: "p_search.json", path: "sandbox_artifacts/verification_node_000001/p_search.json", size: "2.4 KB", kind: "json", stage: "verification", savedAt: "19:09:34" },
      { name: "analysis.py", path: "sandbox_artifacts/verification_node_000001/analysis.py", size: "5.9 KB", kind: "code", stage: "verification", savedAt: "19:10:04", content: `# Lag robustness across the chronology ensemble\nfor age_model in ensemble:\n    aligned = align_proxies(d18o, d13c, age_model)\n    lags.append(cross_correlation(aligned, max_lag=30))` },
      { name: "result.json", path: "sandbox_artifacts/verification_node_000001/result.json", size: "6.4 KB", kind: "json", stage: "verification", savedAt: "19:13:05", content: `{"execution_success":true,"direction_supported":false,"empirical_support":false,"p_value":0.8012736,"summary":"The predicted multi-decadal lead is not supported."}` },
      { name: "agent.log", path: "sandbox_artifacts/verification_node_000001/agent.log", size: "2.6 KB", kind: "log", stage: "verification", savedAt: "19:13:05", content: "Evaluation complete. The full record favors synchronous coupling (optimal lag = 0 years). The primary lagged ARDL coefficient is not significant after correction." },
    ],
  },
  {
    id: "H2",
    parentId: "root",
    label: "H2 · growth",
    claim: "Annual lamina thickness has an inverted U-shaped relationship with δ18O.",
    status: "supported",
    depth: 1,
    visits: 3,
    value: 1.2,
    reward: 0.91,
    belief: { prior: 0.64, literature: 0.57, seed: 0.91, external: 0.07 },
    verdict: "contradicted",
    empiricalSupport: true,
    summary: "Growth peaks at intermediate hydrological conditions and is suppressed at both wet and dry extremes. The effect survives chronology uncertainty.",
    rationale: "The quadratic term remains negative under HAC correction and in 96.2% of 1,000 age-model realizations. However, the qualifying independent cave record shows a monotonic trend rather than the seed dataset’s inverted U-shape.",
    metrics: [
      { label: "Quadratic β", value: "−13.92" },
      { label: "HAC p", value: "0.0395" },
      { label: "Robust runs", value: "96.2%" },
    ],
    sources: [
      { title: "Annual lamina thickness", source: "Dataset S3.xlsx", kind: "seed", note: "1,025 annual measurements" },
      { title: "Stable isotope record", source: "Dataset S2.xlsx", kind: "seed", note: "Aligned by modeled age" },
      { title: "SISAL v3 cave panel", source: "NOAA NCEI", kind: "external", note: "Seed entity excluded before replication" },
    ],
    code: `model = smf.ols("thickness ~ d18o + I(d18o ** 2)", data=aligned)\nfit = model.fit(cov_type="HAC", cov_kwds={"maxlags": 8})\n\nassert fit.params["I(d18o ** 2)"] < 0\nassert fit.pvalues["I(d18o ** 2)"] < 0.05`,
    whyProposed: "Karst hydrochemistry predicts two plausible growth constraints: dilution under very wet conditions and drought or prior calcite precipitation under very dry conditions. The dataset uniquely pairs annual lamina thickness, δ18O, and 1,000 age-model realizations, making the non-linear claim unusually testable.",
    literatureRationale: "Mechanistic literature makes a unimodal response plausible, but δ18O is not a universal rainfall proxy and ventilation or residence time can decouple it from growth. The data-blind literature belief was moderately positive, not decisive.",
    seedRationale: "The fitted quadratic curvature is negative (β₂ = −13.92) with HAC p = 0.0395. The peak lies inside the observed δ18O range, and 96.2% of chronology realizations retain p < 0.05. All three preregistered seed criteria pass.",
    test: {
      question: "Does annual lamina growth peak at intermediate δ18O and decline toward both observed hydrological extremes?",
      population: "1,001 annual CS01C lamina observations aligned with δ18O across 1,000 BAM chronology realizations.",
      prediction: "Quadratic curvature β₂ is negative, its vertex lies inside the observed δ18O domain, and both tail slopes point toward a central maximum.",
      method: "Quadratic OLS with HAC/Newey–West errors, piecewise segmented regression, AIC comparison, covariate adjustment, and a 1,000-realization chronology ensemble.",
      successCriteria: ["β₂ < 0 with HAC p < 0.05", "Estimated maximum lies within the observed δ18O range", "At least 80% of chronology realizations preserve negative curvature"],
    },
    sandbox: { id: "verification_node_000002", runtime: "Cloud Run · sandbox do", image: "urithiru-sandbox:latest", region: "europe-west1", startedAt: "19:18:06 UTC", duration: "04m 12s", exitCode: 0, stdout: "Completed comprehensive OLS, HAC, piecewise segmented, covariate-adjusted, and 1,000-realization BAM chronological ensemble verification.", stderr: "" },
    logs: [
      { time: "19:18:06.202", level: "info", source: "orchestrator", message: "submitted verification_node_000002 to Cloud Run" },
      { time: "19:18:08.614", level: "success", source: "sandbox", message: "sandbox ready; 7 dataset files mounted read-only" },
      { time: "19:18:21.043", level: "info", source: "verification", message: "literature assessment complete; p_search.json saved" },
      { time: "19:18:22.180", level: "info", source: "sandbox", message: "seed-data gate opened after Phase A artifact check" },
      { time: "19:19:02.771", level: "info", source: "verification", message: "quadratic OLS complete: β₂=-13.9202, p=0.000205" },
      { time: "19:19:07.114", level: "info", source: "verification", message: "HAC correction complete: p=0.039542" },
      { time: "19:19:31.822", level: "info", source: "verification", message: "launched 1,000-realization age-model ensemble" },
      { time: "19:21:54.090", level: "success", source: "verification", message: "ensemble complete: 100% concave; 96.2% significant" },
      { time: "19:22:18.366", level: "success", source: "sandbox", message: "result.json validated; container exited with code 0" },
      { time: "19:22:20.008", level: "info", source: "external", message: "external verification submitted for Guizhouxinv Cave" },
      { time: "19:25:11.632", level: "warning", source: "external", message: "external curvature β₂=+0.0272, opposite direction; verdict contradicted" },
      { time: "19:25:13.144", level: "success", source: "sandbox", message: "external_result.json saved; worker exited with code 0" },
    ],
    artifacts: [
      { name: "goal.txt", path: "sandbox_artifacts/verification_node_000002/goal.txt", size: "13.1 KB", kind: "prompt", stage: "verification", savedAt: "19:18:08" },
      { name: "p_search.json", path: "sandbox_artifacts/verification_node_000002/p_search.json", size: "2.4 KB", kind: "json", stage: "verification", savedAt: "19:18:21", content: `{"search_category_counts":{"definitely false":1,"maybe false":3,"uncertain":8,"maybe true":14,"definitely true":4},"search_rationale":"An inverted U-shaped response is mechanistically plausible but cave-specific confounding remains."}` },
      { name: "deep_analysis.py", path: "sandbox_artifacts/verification_node_000002/deep_analysis.py", size: "4.4 KB", kind: "code", stage: "verification", savedAt: "19:19:00", content: `model = smf.ols("thickness ~ d18o + I(d18o ** 2)", data=aligned)\nfit = model.fit(cov_type="HAC", cov_kwds={"maxlags": 8})\n\nprint(fit.summary())` },
      { name: "ensemble_analysis.py", path: "sandbox_artifacts/verification_node_000002/ensemble_analysis.py", size: "4.2 KB", kind: "code", stage: "verification", savedAt: "19:19:29", content: `for chronology in bam_ensemble:\n    aligned = align_by_age(lamina, d18o, chronology)\n    fits.append(fit_quadratic_hac(aligned))\n\nrobust_fraction = np.mean([fit.pvalue < .05 for fit in fits])` },
      { name: "full_1000_ensemble.py", path: "sandbox_artifacts/verification_node_000002/full_1000_ensemble.py", size: "2.2 KB", kind: "code", stage: "verification", savedAt: "19:19:31" },
      { name: "result.json", path: "sandbox_artifacts/verification_node_000002/result.json", size: "5.6 KB", kind: "json", stage: "verification", savedAt: "19:22:18", content: `{"execution_success":true,"test_spec_valid":true,"direction_supported":true,"empirical_support":true,"p_value":0.0002050579,"p_value_corrected":0.0004101158,"extracted_metrics":{"quadratic_coefficient_b2":-13.9202,"quadratic_p_value_hac":0.039542,"fraction_significant_p_005":0.962}}` },
      { name: "agent.log", path: "sandbox_artifacts/verification_node_000002/agent.log", size: "2.4 KB", kind: "log", stage: "verification", savedAt: "19:22:18", content: "The evaluation of the candidate hypothesis has been completed across Phase A and Phase B. The inverted U-shaped relationship is robust to dating uncertainty: 100% of realizations exhibit negative curvature and 96.2% achieve p < 0.05." },
      { name: "external_verification_analysis.py", path: "sandbox_artifacts/external_node_000002/external_verification_analysis.py", size: "4.0 KB", kind: "code", stage: "external", savedAt: "19:24:44" },
      { name: "external_result.json", path: "sandbox_artifacts/external_node_000002/external_result.json", size: "1.8 KB", kind: "json", stage: "external", savedAt: "19:25:13", content: `{"source":"Guizhouxinv Cave GZXND21-1; NOAA NCEI Study 38059","category_counts":{"definitely false":23,"maybe false":7,"uncertain":0,"maybe true":0,"definitely true":0},"summary":"The independent record shows a monotonic negative trend and positive quadratic point estimate, contradicting the inverted U-shape."}` },
      { name: "li2023-guizhouxinv.txt", path: "sandbox_artifacts/external_node_000002/li2023-guizhouxinv.txt", size: "98.4 KB", kind: "data", stage: "external", savedAt: "19:23:07" },
    ],
  },
  {
    id: "H3",
    parentId: "root",
    label: "H3 · asymmetry",
    claim: "Weak-monsoon excursions have a faster onset than recovery across chronology realizations.",
    status: "supported",
    depth: 1,
    visits: 1,
    value: 0.73,
    reward: 0.73,
    belief: { prior: 0.52, literature: 0.48, seed: 0.76 },
    verdict: "no independent data",
    empiricalSupport: true,
    summary: "Both target events show onset slopes steeper than recovery slopes under the majority of admissible chronologies.",
    rationale: "Segmented regression was repeated across age realizations; the conclusion is directionally stable but lacks a qualifying external population.",
    metrics: [
      { label: "Onset ratio", value: "1.84×" },
      { label: "Stable runs", value: "89.7%" },
      { label: "Events", value: "2" },
    ],
    sources: [
      { title: "Chronology ensemble", source: "Datasets S5–S7", kind: "seed", note: "Uncertainty-aware event boundaries" },
      { title: "Published event windows", source: "Li et al., 2022", kind: "literature", note: "Event definition only" },
    ],
    code: `for event in event_windows:\n    onset, recovery = segmented_slopes(event)\n    ratios.append(abs(onset) / abs(recovery))\n\nsupport = np.mean(np.asarray(ratios) > 1)`,
  },
  {
    id: "H2.1",
    parentId: "H2",
    label: "H4 · regimes",
    claim: "δ18O and δ13C coupling strengthens specifically during weak-monsoon excursions.",
    status: "running",
    depth: 2,
    visits: 0,
    value: 0,
    belief: { prior: 0.72, literature: 0.63 },
    verdict: "pending",
    summary: "A verifier is fitting regime interactions across both abrupt events and humid baseline intervals.",
    metrics: [
      { label: "Worker", value: "sandbox-04" },
      { label: "Stage", value: "Seed test" },
      { label: "Elapsed", value: "02:14" },
    ],
  },
  {
    id: "H2.2",
    parentId: "H2",
    label: "H5 · coherence",
    claim: "Co-eval stalagmites show stronger spectral coherence at multi-decadal than sub-decadal scales.",
    status: "running",
    depth: 2,
    visits: 0,
    value: 0,
    belief: { prior: 0.83, literature: 0.74 },
    verdict: "pending",
    summary: "Independent literature belief is complete. Wavelet-coherence analysis is running in an isolated worker.",
    metrics: [
      { label: "Worker", value: "sandbox-05" },
      { label: "Stage", value: "Code execution" },
      { label: "Elapsed", value: "01:39" },
    ],
  },
  {
    id: "H3.1",
    parentId: "H3",
    label: "H6 · variance",
    claim: "Interannual growth variability rises during weak-monsoon intervals.",
    status: "queued",
    depth: 2,
    visits: 0,
    value: 0,
    belief: { prior: 0.61, literature: 0.56 },
    verdict: "pending",
    summary: "Selected by UCT and waiting for a verification sandbox.",
    metrics: [
      { label: "Queue", value: "1" },
      { label: "Stage", value: "Waiting" },
      { label: "Expected", value: "~4 min" },
    ],
  },
  {
    id: "H2.1.1",
    parentId: "H2.1",
    label: "candidate",
    claim: "PCP-sensitive intervals explain the observed regime coupling.",
    status: "queued",
    depth: 3,
    visits: 0,
    value: 0,
    verdict: "pending",
    summary: "A novel candidate retained after semantic deduplication. It has not yet been selected for evaluation.",
  },
];

const commonRuns: DiscoveryRun[] = [
  {
    id: "uri_8F2A1C",
    name: "Early Holocene cave dynamics",
    datasetName: "shihua-cave-panel.xlsx",
    datasetSize: "10.5 MB",
    rows: "3,465",
    columns: 42,
    startedAt: "18 min ago",
    status: "running",
    stage: "Empirical verification",
    budget: "standard",
    progress: 62,
    completeNodes: 3,
    totalNodes: 6,
    candidates: 17,
    duplicates: 9,
    verified: 3,
    currentAction: "Testing regime-dependent isotope coupling in 2 sandboxes",
    summary: "Multi-proxy speleothem records from Shihua Cave, with chronology ensembles and a second stalagmite for internal replication.",
    region: "europe-west1",
    nodes: shihuaNodes,
    events: [
      { id: "e6", title: "2 verification workers active", detail: "H4 regime coupling · H5 spectral coherence", time: "now", status: "active" },
      { id: "e5", title: "External evidence replicated H2", detail: "Direction preserved after excluding the seed cave", time: "2m", status: "complete" },
      { id: "e4", title: "H3 supported by seed data", detail: "89.7% of chronology realizations preserve the direction", time: "6m", status: "complete" },
      { id: "e3", title: "H1 refuted", detail: "No significant lead after multiple-test correction", time: "9m", status: "warning" },
      { id: "e2", title: "9 duplicate candidates removed", detail: "Exact and embedding-based semantic checks", time: "13m", status: "complete" },
      { id: "e1", title: "Dataset inspected", detail: "3,465 rows · 42 variables · 1,000 age models", time: "17m", status: "complete" },
    ],
  },
  {
    id: "uri_D41B09",
    name: "Urban particulate signatures",
    datasetName: "medellin-pm25.csv",
    datasetSize: "4.8 MB",
    rows: "128,430",
    columns: 31,
    startedAt: "Yesterday, 16:42",
    status: "completed",
    stage: "Complete",
    budget: "standard",
    progress: 100,
    completeNodes: 6,
    totalNodes: 6,
    candidates: 24,
    duplicates: 13,
    verified: 4,
    currentAction: "Discovery complete",
    summary: "Hourly particulate chemistry and meteorology across four urban monitoring stations.",
    region: "europe-west1",
    nodes: shihuaNodes.map((node) => node.id === "H2.1" || node.id === "H2.2" ? { ...node, status: "supported" as const, belief: { prior: 0.67, literature: 0.59, seed: 0.82, external: 0.7 }, verdict: "replicated" as const, empiricalSupport: true } : node),
    events: [
      { id: "m3", title: "Run completed", detail: "4 of 6 hypotheses empirically supported", time: "Yesterday", status: "complete" },
      { id: "m2", title: "Independent check contradicted H3", detail: "Effect did not transport to the comparison city", time: "Yesterday", status: "warning" },
      { id: "m1", title: "Dataset inspected", detail: "128,430 rows · 31 variables", time: "Yesterday", status: "complete" },
    ],
  },
  {
    id: "uri_A912FE",
    name: "Sepsis intervention timing",
    datasetName: "icu-cohort.parquet",
    datasetSize: "82.3 MB",
    rows: "482,901",
    columns: 76,
    startedAt: "Aug 27, 11:08",
    status: "completed",
    stage: "Complete",
    budget: "deep",
    progress: 100,
    completeNodes: 12,
    totalNodes: 12,
    candidates: 46,
    duplicates: 21,
    verified: 7,
    currentAction: "Discovery complete",
    summary: "De-identified ICU observations and intervention timestamps from a retrospective clinical cohort.",
    region: "us-central1",
    nodes: shihuaNodes,
    events: [
      { id: "s2", title: "Run completed", detail: "7 empirically supported · 3 replicated externally", time: "Aug 27", status: "complete" },
      { id: "s1", title: "Dataset inspected", detail: "482,901 rows · 76 variables", time: "Aug 27", status: "complete" },
    ],
  },
  {
    id: "uri_19E7A4",
    name: "Forest canopy recovery",
    datasetName: "canopy-recovery.csv",
    datasetSize: "18.1 MB",
    rows: "91,204",
    columns: 24,
    startedAt: "Aug 25, 09:31",
    status: "completed",
    stage: "Complete",
    budget: "fast",
    progress: 100,
    completeNodes: 3,
    totalNodes: 3,
    candidates: 11,
    duplicates: 4,
    verified: 2,
    currentAction: "Discovery complete",
    summary: "Longitudinal canopy-cover measurements following wildfire and controlled burns.",
    region: "europe-west1",
    nodes: shihuaNodes.slice(0, 4),
    events: [
      { id: "f2", title: "Run completed", detail: "2 of 3 hypotheses empirically supported", time: "Aug 25", status: "complete" },
      { id: "f1", title: "Dataset inspected", detail: "91,204 rows · 24 variables", time: "Aug 25", status: "complete" },
    ],
  },
];

export function getDemoRuns(): DiscoveryRun[] {
  return structuredClone(commonRuns);
}

export function createDemoRun(datasetName: string, size: string, title: string, budget: DiscoveryRun["budget"]): DiscoveryRun {
  const id = `uri_${Math.random().toString(16).slice(2, 8).toUpperCase()}`;
  return {
    id,
    name: title || datasetName.replace(/\.[^.]+$/, "").replace(/[-_]/g, " "),
    datasetName,
    datasetSize: size,
    rows: "Inspecting…",
    columns: 0,
    startedAt: "just now",
    status: "running",
    stage: "Dataset inspection",
    budget,
    progress: 8,
    completeNodes: 0,
    totalNodes: budget === "fast" ? 3 : budget === "standard" ? 6 : 12,
    candidates: 0,
    duplicates: 0,
    verified: 0,
    currentAction: "Validating schema and profiling variables",
    summary: "Metadata received. The discovery engine is inspecting the uploaded dataset before proposing hypotheses.",
    region: "europe-west1",
    nodes: [{
      id: "root", parentId: null, label: "Dataset", claim: datasetName, status: "root", depth: 0, visits: 0, value: 0,
      summary: "Schema inspection is running. Candidate hypotheses will branch from this node.",
    }],
    events: [
      { id: "new-1", title: "Dataset uploaded", detail: `${datasetName} · ${size}`, time: "now", status: "complete" },
      { id: "new-2", title: "Inspecting dataset", detail: "Profiling schema, missingness, and useful analysis axes", time: "now", status: "active" },
    ],
  };
}

export function formatBytes(bytes: number): string {
  if (bytes < 1024 * 1024) return `${Math.max(1, Math.round(bytes / 1024))} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}
